In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import math
%matplotlib inline 

In [2]:
train=pd.read_csv("train.csv")
test=pd.read_csv("test.csv")
traindf=pd.DataFrame(train)
testdf=pd.DataFrame(test)

traindf.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [3]:
traindf.shape

(891, 12)

In [4]:
testdf.shape

(418, 11)

In [5]:
print(testdf.isnull().sum())

PassengerId      0
Pclass           0
Name             0
Sex              0
Age             86
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
dtype: int64


In [6]:
Fare_avg = np.std(testdf["Fare"])
testdf['Fare'] = testdf['Fare'].fillna(Fare_avg)

testdf['Age'] = testdf.groupby(["Sex","Pclass"])['Age'].transform(lambda x: x.fillna(x.median()))

In [7]:
print(testdf.isnull().sum())

PassengerId      0
Pclass           0
Name             0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          327
Embarked         0
dtype: int64


In [8]:
print(traindf["Pclass"].unique())
print()
print(traindf["Age"].unique())
print()
print(traindf["SibSp"].unique()) 
print()
print(traindf.isnull().sum())

[3 1 2]

[22.   38.   26.   35.     nan 54.    2.   27.   14.    4.   58.   20.
 39.   55.   31.   34.   15.   28.    8.   19.   40.   66.   42.   21.
 18.    3.    7.   49.   29.   65.   28.5   5.   11.   45.   17.   32.
 16.   25.    0.83 30.   33.   23.   24.   46.   59.   71.   37.   47.
 14.5  70.5  32.5  12.    9.   36.5  51.   55.5  40.5  44.    1.   61.
 56.   50.   36.   45.5  20.5  62.   41.   52.   63.   23.5   0.92 43.
 60.   10.   64.   13.   48.    0.75 53.   57.   80.   70.   24.5   6.
  0.67 30.5   0.42 34.5  74.  ]

[1 0 3 4 2 5 8]

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64


In [9]:
traindf.drop(["Name","Ticket","Cabin","PassengerId"],axis=1,inplace=True)
testdf.drop(["Name","Ticket","Cabin","PassengerId"],axis=1,inplace=True)  

In [10]:
sex=pd.get_dummies(traindf["Sex"],drop_first=True)
traindf=pd.concat((traindf,sex),axis=1)
traindf.drop(["Sex"],axis=1,inplace=True)


sex=pd.get_dummies(testdf["Sex"],drop_first=True)
testdf=pd.concat((testdf,sex),axis=1)
testdf.drop(["Sex"],axis=1,inplace=True)

In [11]:
emb=pd.get_dummies(traindf["Embarked"],drop_first=True)
traindf=pd.concat((traindf,emb),axis=1)
traindf.drop(["Embarked"],axis=1,inplace=True)


emb=pd.get_dummies(testdf["Embarked"],drop_first=True)
testdf=pd.concat((testdf,emb),axis=1)
testdf.drop(["Embarked"],axis=1,inplace=True)

In [12]:
pclass=pd.get_dummies(traindf["Pclass"],drop_first=True)
traindf=pd.concat((traindf,pclass),axis=1)
traindf.drop(["Pclass"],axis=1,inplace=True)


pclass=pd.get_dummies(testdf["Pclass"],drop_first=True)
testdf=pd.concat((testdf,pclass),axis=1)
testdf.drop(["Pclass"],axis=1,inplace=True)

In [13]:
traindf.head()

Survived   Age  SibSp  Parch     Fare  male  Q  S  2  3
0         0  22.0      1      0   7.2500     1  0  1  0  1
1         1  38.0      1      0  71.2833     0  0  0  0  0
2         1  26.0      0      0   7.9250     0  0  1  0  1
3         1  35.0      1      0  53.1000     0  0  1  0  0
4         0  35.0      0      0   8.0500     1  0  1  0  1

In [14]:
testdf.head()

Age  SibSp  Parch     Fare  male  Q  S  2  3
0  34.5      0      0   7.8292     1  1  0  0  1
1  47.0      1      0   7.0000     0  0  1  0  1
2  62.0      0      0   9.6875     1  1  0  1  0
3  27.0      0      0   8.6625     1  0  1  0  1
4  22.0      1      1  12.2875     0  0  1  0  1

In [15]:
print(np.std(traindf["Age"]))
traindf["Age"].dropna(inplace=True)

print(np.std(testdf["Age"]))
testdf["Age"].dropna(inplace=True)

14.516321150817317
13.023249697548293


In [16]:
age_scale_train=np.log(traindf["Age"])
age_scale_test=np.log(testdf["Age"])

In [17]:
traindf.drop(["Age"],axis=1, inplace=True)
testdf.drop(["Age"],axis=1, inplace=True)

In [18]:
traindf=pd.concat((traindf,age_scale_train),axis=1)
testdf=pd.concat((testdf,age_scale_test),axis=1)

In [19]:
traindf.dropna(inplace=True)

In [20]:
gender_submission = pd.read_csv("gender_submission.csv")
ytest = pd.DataFrame(gender_submission)

d = {"PassengerId":[] , "Survived":[]  }
Results = pd.DataFrame(d)
Results["PassengerId"] = ytest["PassengerId"]

ytest = ytest["Survived"]

In [21]:
print(traindf.shape)
print(testdf.shape)
print(ytest.shape)

(714, 10)
(418, 9)
(418,)


In [22]:
##LogisticRegression

In [23]:
from sklearn.model_selection import train_test_split
xtrain=traindf.drop("Survived", axis=1)
ytrain=traindf["Survived"]

In [24]:
from sklearn.linear_model import LogisticRegression
logmodel=LogisticRegression()
logmodel.fit(xtrain,ytrain) 

C:\Users\DELL\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [25]:
predictions=logmodel.predict(testdf)

In [26]:
from sklearn.metrics import accuracy_score
accuracy_score(ytest,predictions)

0.9330143540669856

In [27]:
Results["Survived"] = predictions

In [28]:
Results.head(20)

PassengerId  Survived
0           892         0
1           893         0
2           894         0
3           895         0
4           896         1
5           897         0
6           898         1
7           899         0
8           900         1
9           901         0
10          902         0
11          903         0
12          904         1
13          905         0
14          906         1
15          907         1
16          908         0
17          909         0
18          910         1
19          911         1

In [29]:
from sklearn.metrics import confusion_matrix
res=confusion_matrix(ytest,predictions)
res
tn,tp,fn,fp=confusion_matrix(ytest,predictions).ravel()
tn,tp,fn,fp

(255, 11, 17, 135)

In [30]:
Results.shape

(418, 2)

In [31]:
Results.to_csv('answer.csv', encoding='utf-8', index=False)

In [32]:
######RandomForest

In [33]:
from sklearn.ensemble import RandomForestClassifier
from sklearn import model_selection

In [34]:
randomclassifier=RandomForestClassifier(n_estimators=200,criterion='entropy')
randomclassifier.fit(xtrain,ytrain)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='entropy',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=200,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [35]:
predictions = randomclassifier.predict(testdf)

In [36]:
predictions.shape

(418,)

In [37]:
Results["Survived"] = predictions

In [38]:
Results.shape

(418, 2)

In [39]:
Results.to_csv('randomforest.csv', encoding='utf-8', index=False)

In [40]:
## SVM

In [41]:
from sklearn.svm import SVC # "Support vector classifier"  
classifier = SVC(kernel='linear', random_state=0)  
classifier.fit(xtrain, ytrain)  

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='linear', max_iter=-1, probability=False, random_state=0,
    shrinking=True, tol=0.001, verbose=False)

In [42]:
y_pred= classifier.predict(testdf)

In [45]:
from sklearn.metrics import confusion_matrix  
cm= confusion_matrix(ytest, y_pred) 
print(cm)

[[260   6]
 [  4 148]]


In [46]:
Results["Survived"] = y_pred

In [49]:
Results.shape

(418, 2)

In [50]:
Results.to_csv('svm.csv', encoding='utf-8', index=False)